config/routes.rb
P2pTraining::Application.routes.draw do
  ActiveAdmin.routes(self)

  get "catalogs/index"

  get "catalog/view"

  devise_for :users, :controllers => {:registrations => 'registrations', :confirmations => 'confirmations'}

  get "home/index"

  match 'catalog/:id' => "catalog#view", :as => :catalog

  resource :profile do
    get :my_invitations
  end

  resources :invitations

  resources :courses, :only => [:index, :show] do
    collection do
      get :latest, :hot
    end
    member do
      get :finished_campaigns
    end

    resources :comments
  end

  resources :campaigns do
    resources :orders do
      collection do
        post :verify_coupon
        get :verify_coupon
      end

    end
  end

  resources :orders do

    member do
      get :confirm_payment
      post :pay
      post :cancel
      post :apply_to_refund
    end
  end

  resources :favorites

  resources :errors, :only => [:show]

  match 'services' => "company#services"
  match 'about_us' => "company#about_us"
  match 'join_us' => "company#join_us"
  match 'help' => "company#help"
  match 'trainers' => "company#trainers"

  match '/payments/notify' => "payments#notify", :via => [:get, :post]
  match '/payments/done' => "payments#done", :via => [:get, :post]

  resource :assets do
    member do
      post :upload_image
      get :browse_images
    end
  end

  namespace :admin do
    resources :catalogs do
      member do
        post :enable
        post :disable
      end
    end

    resources :courses do
      resources :campaigns do
        collection do
          get :search
          post :search
        end
        member do
          post :absent, :present, :finish
          get :absent, :present
        end

      end
    end

    resources :users do
      collection do
        get :search
      end
    end

    resources :locations

    resources :orders

    resources :payments

    resource :dashboards

    resources :custom_emails

    resources :coupons

    root :to => "dashboards#show"
  end

  root :to => "home#index"

end

app/models/invitation.rb
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Invitation
#
# Name                           SQL Type             Null    Default Primary
# ------------------------------ -------------------- ------- ------- -------
# id                             int(11)              false           true   
# user_id                        int(11)              true                   
# friend_email                   varchar(255)         true                   
# friend_name                    varchar(255)         true                   
# my_name                        varchar(255)         true                   
# content                        text                 true                   
# last_resend_time               datetime             true                   
# signed_up                      tinyint(1)           true                   
# created_at                     datetime             true                   
# updated_at                     datetime             true                   
#
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

class Invitation < ActiveRecord::Base

  validates_presence_of :friend_email, :friend_name, :my_name
  validates :friend_email, :email_format => true

  belongs_to :user


end

app/controllers/invitations_controller.rb
#encoding: utf-8

class InvitationsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :load_user

  def index
    @invited_users = User.invited_users(@user.username).order('created_at DESC')
  end

  def new
    @invitation = Invitation.new({:user => @user, :my_name => @user.username})
  end

  def create
    @invitation = Invitation.new(params[:invitation])
    @invitation.user = @user
    if @invitation.save
      InvitationMailer.invite(@invitation).deliver
      redirect_to({:action => "index"}, :notice => "邀请发送成功!")
    else
      render "new"
    end
  end

  def invite
    user = User.find_by_username( params[:id] )
    session['reference_to'] = user.username unless user.nil?
    redirect_to new_user_registration_path
  end

  private
  def load_user
    @user = current_user
  end

end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/index.html.haml
%h1 我的推广

= show_msg

%p= link_to '邀请朋友', new_invitation_path

%p 有效推广数(帐号已激活): #{valid_invitations_count(@user)}

%p 课程点数: #{course_credits(@user)}

%p 已接受邀请的推广
#prmotions
  %table
    %thead
      %tr
        %th 帐号
        %th 注册时间
        %th 状态
    %tbody
      - @invited_users.each do |invited_user|
        %tr
          %td
            #{invited_user.username} (#{mail_to invited_user.email})
          %td
            = invited_user.created_at
          %td
            - if invited_user.confirmed_at.nil?
              未激活
            - elsif (paid_count = invited_user.paid_orders.size) > 0
              已报名并付款 #{paid_count} 门课程
            - elsif (pending_count = invited_user.pending_payment_orders.size ) > 0
              已报名但未付款 #{pending_count} 门课程
            - else
              尚未报名课程

app/views/invitations/new.html.haml
%h1 邀请朋友

= form_for @invitation, :validate => true do |f|
  %fieldset
    %p/

    #field_email.field
      .required_field_label= f.label :friend_email
      = f.text_field :friend_email

    #field_email.field
      .required_field_label= f.label :friend_name
      = f.text_field :friend_name

    #field_email.field
      .required_field_label= f.label :my_name
      = f.text_field :my_name

    = f.submit t('label.submit')


- content_for :page_include_scripts do
  = javascript_include_tag 'rails.validations',
                           'i18n/messages-zh-CN',
                           'rails.validations.custom'

- content_for :page_inline_scripts do
  :javascript
    $(document).ready(function(){
      $('#invitation_friend_email').change(function(){
        friend_email = $.trim($('#invitation_friend_email').val());
        friend_name = $.trim($('#invitation_friend_name').val());
        if (friend_email.length > 0 && friend_name.length == 0) {
          $('#invitation_friend_name').val(friend_email).data("changed", true).trigger('focusout');
          //$('#invitation_friend_name').trigger('focusout');
        }
      })
    })