config/routes.rb
P2pTraining::Application.routes.draw do
  ActiveAdmin.routes(self)

  get "catalogs/index"

  get "catalog/view"

  devise_for :users, :controllers => {:registrations => 'registrations', :confirmations => 'confirmations'}

  get "home/index"

  match 'catalog/:id' => "catalog#view", :as => :catalog

  resource :profile do
    get :my_invitations
  end

  resources :invitations

  resources :courses, :only => [:index, :show] do
    collection do
      get :latest, :hot
    end
    member do
      get :finished_campaigns
    end

    resources :comments
  end

  resources :campaigns do
    resources :orders do
      collection do
        post :verify_coupon
        get :verify_coupon
      end

    end
  end

  resources :orders do

    member do
      get :confirm_payment
      post :pay
      post :cancel
      post :apply_to_refund
    end
  end

  resources :favorites

  resources :errors, :only => [:show]

  match 'services' => "company#services"
  match 'about_us' => "company#about_us"
  match 'join_us' => "company#join_us"
  match 'help' => "company#help"
  match 'trainers' => "company#trainers"

  match '/payments/notify' => "payments#notify", :via => [:get, :post]
  match '/payments/done' => "payments#done", :via => [:get, :post]

  resource :assets do
    member do
      post :upload_image
      get :browse_images
    end
  end

  namespace :admin do
    resources :catalogs do
      member do
        post :enable
        post :disable
      end
    end

    resources :courses do
      resources :campaigns do
        collection do
          get :search
          post :search
        end
        member do
          post :absent, :present, :finish
          get :absent, :present
        end

      end
    end

    resources :users do
      collection do
        get :search
      end
    end

    resources :locations

    resources :orders

    resources :payments

    resource :dashboards

    resources :custom_emails

    resources :coupons

    root :to => "dashboards#show"
  end

  root :to => "home#index"

end

app/models/catalog.rb
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Catalog
#
# Name                           SQL Type             Null    Default Primary
# ------------------------------ -------------------- ------- ------- -------
# id                             int(11)              false           true   
# name                           varchar(255)         true                   
# description                    varchar(255)         true                   
# enabled                        tinyint(1)           true    true           
# parent_catalog_id              int(11)              true                   
# created_at                     datetime             true                   
# updated_at                     datetime             true                   
#
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

class Catalog < ActiveRecord::Base

  belongs_to :parent_catalog, :class_name => "Catalog", :foreign_key => "parent_catalog_id"

  has_many :sub_catalogs, :class_name => "Catalog", :foreign_key => "parent_catalog_id"
  has_and_belongs_to_many :courses

  validates_presence_of :name
  validates_uniqueness_of :name

  scope :root_catalogs, where(:parent_catalog_id => nil).order(:name)
  scope :active_catalogs, where(:enabled => true)
  scope :active_root_catalogs, root_catalogs.active_catalogs

  def active_sub_catalogs
    self.sub_catalogs.active_catalogs
  end

  def active_courses
    self.courses.where(:status.ne => 'close')
  end

end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  def view
    @catalog = Catalog.find(params[:id])
  end

end

app/helpers/admin/catalogs_helper.rb
#encoding: utf-8

module Admin::CatalogsHelper

  def generate_enable_link(catalog)
    if catalog.enabled
      link_to "禁用", disable_admin_catalog_path(catalog), :method => 'post'
    else
      link_to "启用", enable_admin_catalog_path(catalog), :method => 'post'
    end
  end

end

app/helpers/catalog_helper.rb
module CatalogHelper
  def status_options
    {
        t("label.status.open") => :"open",
        t("label.status.close") => :"close",
        t("label.status.suspend") => :"suspend",
        t("label.status.pending") => :"pending",
    }
  end
end

app/views/catalog/_course.html.haml
- courses.each do |course|
  #course(id="#{course.id}")
    #course_avatar.span-5.suffix-1
      = image_tag course.avatar_url(:thumb).to_s

    #course_main.span-12
      #course_title
        %h2= course.course_name
        #catalogs
          所属目录:
          = course.catalogs.collect {|c| c.name}.join(", ")

      #course_description
        != course.short_description

      #price
        价格:
        %span.delete #{course.price}
        %br/
        优惠价:
        %b= course.discount_price

      #info
        - if course.favorites.size > 0
          共
          %b #{course.favorites.size}
          人关注 &nbsp;&nbsp;



      = link_to t("label.detail"), course
      |
      = link_to t("label.add_to_favorite"), favorites_path(:course_id => course.id), :method => 'POST'
      |
      = link_to t("label.register_now"), new_campaign_order_path(course)
      %br/
      %b
        %span(id="comment_count_#{course.id}")= course.comments.count
      评论
      = link_to "查看", course_comments_path(course), :id => "show_comments_#{course.id}", :remote => true
      - if user_signed_in?
        = link_to "说两句", new_course_comment_path(course), :remote => true
      #comments_panel
        .new_comment(id="course_#{course.id}_new_comment")
        .comments(id="comments_course_#{course.id}")

  %hr

app/views/catalog/view.html.haml
%h1 #{@catalog.name}

//= render 'course', :courses => @catalog.active_courses
#courses
  %ul
    = render :partial => 'courses/course_item', :collection => @catalog.active_courses