config/routes.rb
P2pTraining::Application.routes.draw do
  ActiveAdmin.routes(self)

  get "catalogs/index"

  get "catalog/view"

  devise_for :users, :controllers => {:registrations => 'registrations', :confirmations => 'confirmations'}

  get "home/index"

  match 'catalog/:id' => "catalog#view", :as => :catalog

  resource :profile do
    get :my_invitations
  end

  resources :invitations

  resources :courses, :only => [:index, :show] do
    collection do
      get :latest, :hot
    end
    member do
      get :finished_campaigns
    end

    resources :comments
  end

  resources :campaigns do
    resources :orders do
      collection do
        post :verify_coupon
        get :verify_coupon
      end

    end
  end

  resources :orders do

    member do
      get :confirm_payment
      post :pay
      post :cancel
      post :apply_to_refund
    end
  end

  resources :favorites

  resources :errors, :only => [:show]

  match 'services' => "company#services"
  match 'about_us' => "company#about_us"
  match 'join_us' => "company#join_us"
  match 'help' => "company#help"
  match 'trainers' => "company#trainers"

  match '/payments/notify' => "payments#notify", :via => [:get, :post]
  match '/payments/done' => "payments#done", :via => [:get, :post]

  resource :assets do
    member do
      post :upload_image
      get :browse_images
    end
  end

  namespace :admin do
    resources :catalogs do
      member do
        post :enable
        post :disable
      end
    end

    resources :courses do
      resources :campaigns do
        collection do
          get :search
          post :search
        end
        member do
          post :absent, :present, :finish
          get :absent, :present
        end

      end
    end

    resources :users do
      collection do
        get :search
      end
    end

    resources :locations

    resources :orders

    resources :payments

    resource :dashboards

    resources :custom_emails

    resources :coupons

    root :to => "dashboards#show"
  end

  root :to => "home#index"

end

app/views/common/_ad_01.html.haml
%p(style="width:100%;background-color:#ccccee;padding-top:10px;")
  .ad(style="width:380px;text-align:right;")
    %span{:style => "font-size:14px;color:#003399;"}
      我们不是学校教师，我们是
      %span{:style => "font-size:18px;color:#cc33e5;"}> 多年
      工作经验的
      %span{:style => "font-size:18px;color:#cc33e5;"}> IT专业人员
      。
    %br/
    %span{:style => "color:#003399;"}
    %span{:style => "font-size:14px;color:#003399;"} &nbsp;&nbsp;
    %span{:style => "font-size:14px;color:#003399;"}
      我们分享的不仅仅是理论，更多的是
      %span{:style => "color:#cc33e5;font-size:18px;"}> 真实的工作经验
      。
      %br/
    %span{:style => "font-size:14px;color:#003399;"}
      帮助您更顺利的工作，更快捷的
      %span{:style => "font-size:18px;color:#cc33e5;"}> 加薪升职
      。
    %br/

app/views/common/_ad_flash.html.haml
.span-24.last
  #flash(style="padding-top:30px;")
    :javascript
      var focus_width=950;
      var focus_height=136;
      var text_height=0;
      var swf_height = focus_height+text_height;
      var pics = "";
      var links = "";
      var texts = "";


      pics += "images/01.jpg";
      links += "/about_us";
      texts += "";

      pics += "|";
      links += "|";
      texts += "|";

      pics += "images/04.jpg";
      links += "/trainers";
      texts += "";

      pics += "|";
      links += "|";
      texts += "|";

      pics += "images/02.jpg";
      links += "product-02.htm";
      texts += "";

      pics += "|";
      links += "|";
      texts += "|";

      pics += "images/03.jpg";
      links += "product.htm";
      texts += "";

      document.write('<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="'+ focus_width +'" height="'+ swf_height +'">');
      document.write('<param name="allowScriptAccess" value="sameDomain"><param name="movie" value="images/focus.swf"><param name="quality" value="high"><param name="bgcolor" value="#FFFFFF">');
      document.write('<param name="menu" value="false"><param name=wmode value="opaque">');
      document.write('<param name="FlashVars" value="pics='+pics+'&links='+links+'&texts='+texts+'&borderwidth='+focus_width+'&borderheight='+focus_height+'&textheight='+text_height+'">');
      document.write('<embed src="images/focus.swf" wmode="opaque" FlashVars="pics='+pics+'&links='+links+'&texts='+texts+'&borderwidth='+focus_width+'&borderheight='+focus_height+'&textheight='+text_height+'" menu="false" ?bgcolor="#ffffff" quality="high" width="'+ focus_width +'" height="'+ swf_height +'" allowScriptAccess="sameDomain" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />');  document.write('</object>');

app/views/common/_catalog_nav_bar.html.haml
#inner-header
  %ul
    - catalogs.each do |catalog|
      %li
        = link_to catalog.name, catalog_path(catalog)

app/views/common/_error.html.haml
%h1 出错啦
= show_msg

%br/

app/views/common/_hot_photos.html.haml
-#
  #hot_photos
    %h5 课间留影
    %ul
      - hot_photos().each do |photo|
        %li
          = link_to photo.image_url.to_s, :class => "hot_photos", :rel => "hot_photos", :title => "#{photo.description}" do
            = image_tag photo.image_url(:thumb).to_s


#latest_hot_photos.span-24.last
  #title.hot_photos_title
    课间留影
    &nbsp;&nbsp;
    = link_to "更多", "/albums"
  #hot_photos.span-24.last(style="padding:0px; border: 0px solid #E9E9E9; height:155px; background-color: #E9E9E9")
    %ul
      - hot_photos().each do |photo|
        %li
          = link_to photo.image_url.to_s, :class => "hot_photos", :rel => "hot_photos", :title => "#{photo.description}" do
            = image_tag photo.image_url().to_s, :width => "230px", :height => "150px"


= stylesheet_link_tag '/fancybox/jquery.fancybox-1.3.4.css'
= javascript_include_tag '/fancybox/jquery.fancybox-1.3.4.pack.js'
= javascript_include_tag '/fancybox/jquery.mousewheel-3.0.4.pack.js'

:javascript
  $(document).ready(function(){
    $("a.hot_photos").fancybox();
  });

app/views/common/_model_errors.html.haml
#error_explanation.error
  %h2= "无法保存, #{errors.count}处错误:"
  %ul
    - errors.full_messages.each do |msg|
      %li= msg

app/views/common/_page_footer.html.haml
#footer
  .container
    %p
      关于我们 | 服务 | 帮助 ....
    %center
      Copyright @2011 深圳市良才咨询培训有限公司

app/views/common/_page_footer_new.html.haml
#footer.span-24.last
  关于良才 | 联系良才咨询培训 | 服务热线：86-755-89891680
  %br/
  Copyright @2011 深圳市良才咨询培训有限公司  版权所有 粤ICP备09115785号

.span-24.last.space-13px

app/views/common/_page_header.html.haml
#header.span-24(style="padding-bottom:40px;")
  .span-24.last
    = image_tag 'top_banner.jpg'
  .span-12
    \.
  .span-12.last
    = render "common/user_nav"

  .span-24.last
    = render "common/page_menu"

//  #catalog_nav.header.span-24.last(style="margin-top:35px;")
//    = render "common/catalog_nav_bar", :catalogs => Catalog.active_root_catalogs

app/views/common/_page_left.html.haml
#left_box(style="min-height:450px;")
  .recommended
  .inner_box
    %h5
      %b 课程类别
    #catalog_nav
      %ul
        %li.li_star_orange(style="display: list-item;")= link_to "最新课程", latest_courses_path
        %li.li_star_orange(style="display: list-item;")= link_to "热门课程", hot_courses_path
        - Catalog.active_root_catalogs.each do |catalog|
          %li
            = link_to catalog.name, catalog_path(catalog)
  .recommended
  .inner_box
    %h5
      %b 标签
    %ul
      %li JAVA
      %li .Net
      %li Ruby

app/views/common/_page_menu_new.html.haml
%div(min-height="4")
#menu
  .wrapper
    %ul
      %li(style="width:250px;")= link_to "P2P-TRAINING.INFO", "#"
      %li= link_to '首页', root_path
      %li= link_to '服务', services_path
      %li= link_to '课程', courses_path
      %li= link_to '讲师', trainers_path
      %li= link_to '关于我们', about_us_path
      %li= link_to '加入我们', join_us_path
      %li= link_to '帮助', help_path

app/views/common/_panel.html.haml
.span-8
  #panel_title_bar
    .panel_left
    .panel_middle
      = title
    .panel_right
  .panel_content(style="height:180px;")
    = body

app/views/common/_show_msg.html.haml
- if flash[:notice] then
  #notice.success
    %h2
      = image_tag("icons/tick.png")
      = flash[:notice]

- elsif flash[:alert] then
  #notice.error
    %h2
      = image_tag("icons/cross.png")
      = flash[:alert]

- elsif flash[:info] then
  #notice.notice
    %h2
      = image_tag("icons/information.png")
      = flash[:info]

- elsif flash[:error] then
  #notice.error
    %h2
      = image_tag("icons/cross.png")
      = flash[:error]

app/views/common/_user_nav.html.haml
#user_nav
  - unless user_signed_in?
    = link_to t('label.login'), new_user_session_path
    %span &nbsp;&nbsp;
    = link_to t('label.sign_up'), new_user_registration_path
  - else
    .span
      = t('label.login_as')
      = link_to "#{current_user.username}", edit_profile_path
      &nbsp;|&nbsp;
      = link_to t('label.logout'), destroy_user_session_path
      &nbsp;|&nbsp;
      = link_to t('label.my_favorites'), favorites_path
      &nbsp;|&nbsp;
      = link_to t('label.my_orders'), orders_path
      &nbsp;|&nbsp;
      = link_to t('label.my_invitations'), invitations_path
      - if current_user.role?('admin')
        &nbsp;|&nbsp;
        = link_to "管理", '/admin'